# rocks.toml — Plugin declaration for rocks.nvim

# -----------------------------------------------------------------------------
# LuaRocks dependencies (pure Lua modules, non-Neovim plugins)
# -----------------------------------------------------------------------------
[rocks]
# e.g. toml parser for Lua scripts 
# toml = "0.1.0"

# -----------------------------------------------------------------------------
# Neovim plugins (core plugins, installed via rocks.nvim)
# -----------------------------------------------------------------------------
[plugins]
"rocks.nvim"            = "2.44.0"
"rocks-edit.nvim"       = "scm"
"rocks-treesitter.nvim" = "1.3.0"
"rocks-git.nvim"        = "2.5.3"
"rocks-config.nvim"     = "3.1.1"
tree-sitter-toml        = "0.0.31"
"neodev.nvim"           = "3.0.0"
neorg                   = "9.3.0"
nvim-cmp                = "scm"
cmp-nvim-lsp            = "scm"
"lspkind.nvim"          = "scm"
cmp-buffer              = "scm"
cmp-path                = "scm"
cmp-cmdline             = "scm"
cmp_luasnip             = "scm"
luasnip                 = "2.4.0"
friendly-snippets       = "scm"
nvim-web-devicons       = "0.100"
tree-sitter-python      = "0.0.46"

# Theme plugins (some available via rocks, others only via git)
"dracula.nvim"          = "scm"
catppuccin              = "0.1.0"
"onedarkpro.nvim"       = "2.17.1"
"monokai.nvim"          = "scm"
"rose-pine"             = { git = "rose-pine/neovim", rev = "v3.0.2" }
"nord"                  = { git = "shaunsingh/nord.nvim", rev = "80c1e5321505aeb22b7a9f23eb82f1e193c12470" }
"iceberg"               = { git = "cocopon/iceberg.vim", rev = "1.0^{}" }

# Telescope extensions
"telescope.nvim"           = "scm"
"telescope-ui-select.nvim" = "scm"

# -----------------------------------------------------------------------------
# Plugin-specific Git refs (for non-rocks plugins or custom forks)
# -----------------------------------------------------------------------------
[plugins.nvim-terminal]
git = "s1n7ax/nvim-terminal"
rev = "e058de4b8029d7605b17275f30f83be8f8df5f62"

[plugins.cmp-nvim-lua]
git = "hrsh7th/cmp-nvim-lua"
rev = "f12408bdb54c39c23e67cab726264c10db33ada8"

[plugins.cmp-spell]
git = "f3fora/cmp-spell"
rev = "694a4e50809d6d645c1ea29015dad0c293f019d6"

[plugins.cmp-nvim-lsp-document-symbol]
git = "hrsh7th/cmp-nvim-lsp-document-symbol"
rev = "f94f7ba948e32cd302caba1c2ca3f7c697fb4fcf"

[plugins.cmp-nvim-lsp-signature-help]
git = "hrsh7th/cmp-nvim-lsp-signature-help"
rev = "031e6ba70b0ad5eee49fd2120ff7a2e325b17fa7"

# -----------------------------------------------------------------------------
# Treesitter settings (parser installation)
# -----------------------------------------------------------------------------
[treesitter]
auto_install    = "prompt"   # options: true | false | "prompt"
auto_highlight = [
  "lua",
  "python",
  "rust",
  "haskell",
  "toml",
  "dhall"
]

[treesitter.parser_map]
PKGBUILD = "bash"
cls      = "latex"
sty      = "latex"

# -----------------------------------------------------------------------------
# Core config
# -----------------------------------------------------------------------------
[config]
plugins_dir = "plugins/"
auto_setup  = false

# -----------------------------------------------------------------------------
# Plugin configuration (via rocks-config.nvim)
# -----------------------------------------------------------------------------
[plugins.nvim-notify]
version = "3.15.0"
config  = "plugins.ui.nvim-notify.config"

[plugins."nvim-tree.lua"]
version = "1.6.0"
config  = "plugins.ui.nvim-tree.config"

[plugins."staline.nvim"]
version = "scm"
config  = "plugins.ui.staline.config"

[plugins.dashboard-nvim]
version = "scm"
config  = "plugins.ui.dashboard.config"

[plugins."indent-blankline.nvim"]
version = "3.9.0"
config  = "plugins.autocomplete.indent.config"

[bundles.telescope]
items  = ["telescope.nvim", "telescope-ui-select.nvim"]
config = "plugins.ui.telescope.config"

[plugins."ultimate-autopair.nvim"]
version = "scm"
config  = "plugins.autocomplete.autopair.config"

# -----------------------------------------------------------------------------
# LSP & completion
# -----------------------------------------------------------------------------
[plugins."mason-lspconfig.nvim"]
version = "scm"
config  = "plugins.autocomplete.lspconfig"

[bundles.cmp]
items = [
  "lspkind.nvim",
  "nvim-cmp",
  "cmp-nvim-lsp",
  "cmp-buffer",
  "cmp-path",
  "cmp-cmdline",
  "luasnip",
  "cmp_luasnip",
  "friendly-snippets",
  "neodev.nvim"
]
config = "plugins.autocomplete.cmp"

[plugins."trouble.nvim"]
version = "3.7.1"
config  = "plugins.autocomplete.trouble.config"


