# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:

# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.37.0"
"rocks-edit.nvim" = "scm"
"rocks-treesitter.nvim" = "1.0.3"
"rocks-git.nvim" = "2.0.1"
"rocks-config.nvim" = "2.2.0"
tree-sitter-toml = "0.0.2"
"neodev.nvim" = "3.0.0"
neorg = "9.1.1"
nvim-cmp = "scm"
cmp-nvim-lsp = "scm"
"lspkind.nvim" = "scm"
cmp-buffer = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
cmp_luasnip = "scm"
luasnip = "2.3.0"
friendly-snippets = "scm"
nvim-web-devicons = "0.100"
tree-sitter-python = "0.0.2"
"dracula.nvim" = "scm"
catppuccin = "0.1.0"
"onedarkpro.nvim" = "0.8.0"
"monokai.nvim" = "scm"
"telescope-ui-select.nvim" = "scm"
"telescope.nvim" = "scm"

[plugins.cmp-nvim-lua]
git = "hrsh7th/cmp-nvim-lua"
[plugins.cmp-spell]
git = "f3fora/cmp-spell"
[plugins.cmp-nvim-lsp-document-symbol]
git = "hrsh7th/cmp-nvim-lsp-document-symbol"
[plugins.cmp-nvim-lsp-signature-help]
git = "hrsh7th/cmp-nvim-lsp-signature-help"
[plugins.iceberg] # Theme/ColorSchrome
git = "cocopon/iceberg.vim"
[plugins.nord] # Theme/ColorSchrome
git = "shaunsingh/nord.nvim"
[plugins.rose-pine] # Theme/ColorSchrome
git = "rose-pine/neovim"
name = "rose-pine"


[treesitter]
# auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_highlight = [
  "haskell",
  "dhall",
  "rust",
  "toml",
  "python",
  "lua"
]

auto_install = "prompt" # true | false

[treesitter.parser_map]
# You can add custom filetype to parser mappings.
# Determine the filetype with ':lua =vim.bo[0].filetype'.
# NOTE: You don't actually have to add these examples.
# They are added by default.
PKGBUILD = "bash"
cls = "latex"
sty = "latex"

[config]
plugins_dir = "plugins/"
auto_setup = false

# User Interface Plugins Settings
[plugins.nvim-notify]
version = "3.13.5"
config = "plugins.ui.nvim-notify.config"
[plugins."nvim-tree.lua"]
version = "1.6.0"
config = "plugins.ui.nvim-tree.config"
[plugins."staline.nvim"]
version = "scm"
config = "plugins.ui.staline.config"
[plugins.dashboard-nvim]
version = "scm"
config = "plugins.ui.dashboard.config"
[plugins."indent-blankline.nvim"]
version = "3.9.0"
config = "plugins.autocomplete.indent.config"

[bundles.telescope]
items = [
  "telescope.nvim",
  "telescope-ui-select.nvim"
]
config = "plugins.ui.telescope.config"

[plugins."ultimate-autopair.nvim"]
version = "scm"
config = "plugins.autocomplete.autopair.config"


# LSP & autocomplete System Plugins Settings
[plugins."mason-lspconfig.nvim"]
config = "plugins.autocomplete.lspconfig"
version = "scm"


[bundles.cmp] # Create a bundle called `cmp`
items = [
    "lspkind.nvim",
    "nvim-cmp",
    "cmp-nvim-lsp",
    "cmp-buffer",
    "cmp-path",
    "cmp-cmdline",
    "luasnip",
    "cmp_luasnip",
    "friendly-snippets",
    "neodev.nvim",
 ]
 config = "plugins.autocomplete.cmp"

[plugins."trouble.nvim"]
config = "plugins.autocomplete.trouble.config"
version = "3.6.0"

