# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:

# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.44.0"
"rocks-edit.nvim" = "scm"
"rocks-treesitter.nvim" = "1.3.0"
"rocks-git.nvim" = "2.5.3"
"rocks-config.nvim" = "3.1.1"
tree-sitter-toml = "0.0.31"
"neodev.nvim" = "3.0.0"
neorg = "9.3.0"
nvim-cmp = "scm"
cmp-nvim-lsp = "scm"
"lspkind.nvim" = "scm"
cmp-buffer = "scm"
cmp-path = "scm"
cmp-cmdline = "scm"
cmp_luasnip = "scm"
luasnip = "2.4.0"
friendly-snippets = "scm"
nvim-web-devicons = "0.100"
tree-sitter-python = "0.0.46"
"dracula.nvim" = "scm"
catppuccin = "0.1.0"
"onedarkpro.nvim" = "2.17.1"
"monokai.nvim" = "scm"
"telescope-ui-select.nvim" = "scm"
"telescope.nvim" = "scm"

[plugins.nvim-terminal]
git = "s1n7ax/nvim-terminal"
rev = "e058de4b8029d7605b17275f30f83be8f8df5f62"

"cmp-nvim-lua" = "scm"
"cmp-spell" = "scm"
"cmp-nvim-lsp-document-symbol" = "scm"
"cmp-nvim-lsp-signature-help" = "scm"

[plugins.iceberg]
git = "cocopon/iceberg.vim"
rev = "1.0^{}"

[plugins.nord]
git = "shaunsingh/nord.nvim"
rev = "80c1e5321505aeb22b7a9f23eb82f1e193c12470"

[plugins.rose-pine]
git = "rose-pine/neovim"
rev = "v3.0.2"


[treesitter]
# auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_highlight = [
  "haskell",
  "dhall",
  "rust",
  "toml",
  "python",
  "lua"
]

auto_install = "prompt" # true | false

[treesitter.parser_map]
# You can add custom filetype to parser mappings.
# Determine the filetype with ':lua =vim.bo[0].filetype'.
# NOTE: You don't actually have to add these examples.
# They are added by default.
PKGBUILD = "bash"
cls = "latex"
sty = "latex"

[config]
plugins_dir = "plugins/"
auto_setup = false

# User Interface Plugins Settings
# [plugins.nvim-notify]
# version = "3.15.0"
# config = "plugins.ui.snacks.notify"
# [plugins."nvim-tree.lua"]
# version = "1.6.0"
# config = "plugins.ui.snacks.explorer"
# [plugins."staline.nvim"]
# version = "scm"
# config = "plugins.ui.snacks.statuscolumn"
# [plugins.dashboard-nvim]
# version = "scm"
# config = "plugins.ui.snacks.dashboard"
# [plugins."indent-blankline.nvim"]
# version = "3.9.0"
# config = "plugins.ui.snacks.indent"

# [bundles.telescope]
# items = [
#   "telescope.nvim",
#   "telescope-ui-select.nvim"
# ]
# config = "plugins.ui.snacks.picker"

[plugins."ultimate-autopair.nvim"]
version = "scm"
config = "plugins.autocomplete.autopair.config"


# LSP & autocomplete System Plugins Settings
[plugins."mason-lspconfig.nvim"]
config = "plugins.autocomplete.lspconfig"
version = "scm"


[bundles.cmp] # Create a bundle called `cmp`
items = [
    "lspkind.nvim",
    "nvim-cmp",
    "cmp-nvim-lsp",
    "cmp-buffer",
    "cmp-path",
    "cmp-cmdline",
    "luasnip",
    "cmp_luasnip",
    "friendly-snippets",
    "neodev.nvim",
 ]
 config = "plugins.autocomplete.cmp"

[plugins."snacks.nvim"]
git = "folke/snacks.nvim"
config = "plugins.ui.snacksMain"
version = "scm"

# [plugins."trouble.nvim"]
# config = "plugins.ui.snacks.debug"
# version = "3.7.1"

